version: 0.0
os: linux
files:
  - source: /target/awsproject-1.0-SNAPSHOT.war
    destination: /home/ec2-user/
hooks:
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
    - location: scripts/start_server
      timeout: 300